### ISSUE TITLE
Resize IPD gradient chart 

### ISSUE THREAD

**Issue by rbeatty1** [crvanpollard/IPD_V2#11]
Right now the right side of the IPD gradient chart gets cut off. No need for it to be the entire width of the sidebar, so resizing it seems like a good idea. See attached PNG

![gradient-chart](https://user-images.githubusercontent.com/28264237/36804326-45cc353e-1c88-11e8-8a75-256899ebac43.png)

**Comment by rbeatty1** [comment]
This seems to happen for each of the charts related to each population group. Issues resolves itself if you resize your screen, but is a problem at the initial load.

**Comment by crvanpollard** [comment]
#closed fixed by adding padding to Map-Layers div
