### ISSUE TITLE
Validation and accessibility issues

### ISSUE THREAD

**Issue by jstrangfeld** [crvanpollard/IPD_V2#12]
- [x] element `id` attributes are not unique
- [x] images do not have `alt` tags
- [x] link text color does not have enough contrast
- [x] footer and `.location-list` link hover color is invisible against background
- [x] external links do not use `rel="noopener"`
- [x] base font sizes are smaller than 16px

**Comment by crvanpollard** [comment]
I have pretty much addressed most of the above issues/concerns.
please review and double check (Master is updated with the latest fixes as of 5/3/18)

**Comment by jstrangfeld** [comment]
I  suggest changing link color to `#275c8b` to give enough contrast. You can check other colors here: http://leaverou.github.io/contrast-ratio/#hsla%28208%2C%2056%25%2C%2035%25%2C%201%29-on-white

In addition, `#legend-row` is found multiple times in the document.
