### ISSUE TITLE
Massive GEOJSON file sizes

### ISSUE THREAD

**Issue by jstrangfeld** [crvanpollard/IPD_V2#13]
1. Geometry should be simplified
2. Decimal places truncated
3. Extraneous properties removed

**Comment by crvanpollard** [comment]
The idea/work around is to test directly linking to DVRPC GIS Data Portal GeoJson location for the IPD 2016 dataset. Hopefully this will help with load time and file size

**Comment by seandoesgis** [comment]
https://opendata.arcgis.com/datasets/ab586640e7ab40e58c0615f9355cb35a_0.geojson

**Comment by jstrangfeld** [comment]
The other two files should still be reduced.

**Comment by rbeatty1** [comment]
@jstrangfeld we can just pull from open data and not even use the geojsons for drawing the data. I can make the changes
