### ISSUE TITLE
Update legend title to match indicator

### ISSUE THREAD

**Issue by DVRPCfreight** [crvanpollard/IPD_V2#15]
Legend title should change when map content is update to individual indicators

**Comment by rbeatty1** [comment]
Are you referring to the legend in the bottom-right control element?

**Comment by DVRPCfreight** [comment]
Yes sir. I want to know what is "above" or "below average" scoring. I know it is in sidebar but the static title of "IPD Score Analysis" doesn't tell me is it just the IPD composite or a single indicator.
