### ISSUE TITLE
Indicator modal text

### ISSUE THREAD

**Issue by DVRPCfreight** [crvanpollard/IPD_V2#20]
Every indicator still has holder text `The data for this indicator can be downloaded in the NAME HERE tab.`

**Comment by crvanpollard** [comment]
Waiting for Seandoesgis to publish IPD 2016 GIS dataset to DVRPC GIS Data Portal, once this is done direct link to Data Download will be insert into this holder text

**Comment by seandoesgis** [comment]
https://dvrpc-dvrpcgis.opendata.arcgis.com/datasets/dvrpc-2016-tract-level-indicators-of-potential-disadvantage  DONE

**Comment by crvanpollard** [comment]
I will not have time to get this issue before we launch. @rbeatty1 could you please make sure to add this URL to Home Page and Population Group Modal text. Thanks (CP 5/3/18)
