### ISSUE TITLE
Homepage Redesign

### ISSUE THREAD

**Issue by mmolta** [crvanpollard/IPD_V2#21]
The homepage as is doesn't have much consistency. The cards don't line up, spacing is inconsistent and the arrangement of elements doesn't seem to follow any flow. I cleaned it up and redesigned the homepage, let me know what you think:

old: http://staging.dvrpc.org/webmaps/IPD_V2/index.htm#home

new: http://staging.dvrpc.org/webmaps/IPD_V2/index-2-electric-boogaloo.html#home

I didn't create a branch or pull request because I haven't consulted with anyone and it makes some pretty substantial changes so I want to give you all a chance to look it over before making it official in any way.

**Comment by rbeatty1** [comment]
I like it but I made a few modifications:
    - move the map/download buttons to the bottom-center of the card
    - separate the list items into two columns and center

![new](https://user-images.githubusercontent.com/28264237/36871118-1eaf7a64-1d6f-11e8-8ff4-11719ad96c65.PNG)

**Comment by mmolta** [comment]
Nice, that looks really clean. I just created a branch with this stuff. Feel free to commit your changes into it

**Comment by crvanpollard** [comment]
thanks crew, how does the design flow/look on smaller screens? Alway happy to dance the electric boogaloo

**Comment by rbeatty1** [comment]
See commit e2a6159 in /homepage-rede

**Comment by DVRPCfreight** [comment]
The homepage is currently rendering content with a different column width than the other pages in the application. `Data Disclaimer` and `Methodology` use `col-lg-10` versus homepage which is full width.  Would be nice to have consistency.

**Comment by crvanpollard** [comment]
I have not baked in Electric Boogaloo modifications into Master as of 5/3/18. SNowBomb Riley messed up my plans to do this. Feel free @rbeatty1 and @mmolta to modify and update Homepage as you see fit. Please work w/ Shoshana if you have any ?'s.
