### ISSUE TITLE
Geojson missing mcd and county names

### ISSUE THREAD

**Issue by jstrangfeld** [crvanpollard/IPD_V2#27]
Sean, please join the municipality name (MUN1) and county name (CNTY_NAME) to the dataset.

@seandoesgis

https://github.com/crvanpollard/IPD_V2/blob/8b09891714d22b935b5d9cf80467328541308049/lib/map.js#L274

**Comment by crvanpollard** [comment]
Update IPD dataset on DVRPC Open Data Portal to include MCD and County names. This is important information for users accessing and review IPD scores and analysis for their desired township or borough.

**Comment by crvanpollard** [comment]
IPD 2016 feature class with MCD and CNTY values can be found here: U:\_OngoingProjects\EJ\2015_IPD\NewMethodology\_WebMap\IPD_2016_geojson.shp
attribute fields that need to be included: MUN1, MUN2, MUN3, CNTY_NAME
