### ISSUE TITLE
jQuery known security vulnerabilities

### ISSUE THREAD

**Issue by jstrangfeld** [crvanpollard/IPD_V2#32]
jQuery 1.10 should be upgraded as it has known security vulnerabilities. jQuery 3 is designed to support IE9+ and last version browsers. An upgrade guide is available: https://jquery.com/upgrade-guide/3.0/

Also, is jQuery UI used here? If not, it should removed. Otherwise, it also needs to be upgraded to the latest version.

**Comment by crvanpollard** [comment]
jQuery UI is used for the Slider Opacity Bar to change IPD Map layer transparency
