### ISSUE TITLE
Tracts with no data are being displayed incorrectly 

### ISSUE THREAD

**Issue by rbeatty1** [crvanpollard/IPD_V2#34]
There are several tracts that do not contain any data and have values of -9999. They are currently being displayed as "well below average" when it should be made clear that they are not on the spectrum of analysis.

**Comment by jstrangfeld** [comment]
Ideally, these census tracts should be deleted from the dataset. @seandoesgis

As an alternative, they can be filtered out when the geojson is loaded by checking the attribute values. This will leave empty holes in the map, which I think would be an acceptable representation and prevents them from being clicked at all.

If gaps in the region is not a good solution, we can simply replace all -99999 values with "N/A" in the sidebar. However, an appropriate symbology for missing data will be needed for the map layers.

**Comment by seandoesgis** [comment]
Records with no data have been removed.
